---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp-hardcode
  namespace: testapp
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-hardcode
  namespace: testapp
  labels:
    app: testapp-hardcode
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: testapp-hardcode
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp-hardcode
  name: testapp-hardcode
  namespace: testapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-hardcode
  template:
    metadata:
      labels:
        app: testapp-hardcode
    spec:
      serviceAccountName: testapp-hardcode
      containers:
      - image: quincycheng/testapp:latest
        imagePullPolicy: Always
        name: testapp
        env:
          - name: DBAddress
            value: "mysql.quincycheng.com"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "testapp"
          - name: DBPassword
            value: "Cyberark1"
        ports:
        - containerPort: 3000
          name: http
